// ── Firebase Options — PLACEHOLDER ───────────────────────────────────────────
// This file is auto-generated by FlutterFire CLI after Firebase setup.
// DO NOT use these placeholder values in production — they are non-functional.
//
// To activate Firebase:
//   1. Create Firebase project "mortgageus" at console.firebase.google.com
//   2. Register Android app: com.mortgageus.calculator
//   3. Register iOS app: com.mortgageus.calculator
//   4. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   5. Run: flutterfire configure
//      → Generates this file with real values + google-services.json + GoogleService-Info.plist
//   6. Add firebase_core, firebase_analytics, firebase_crashlytics to pubspec.yaml
//   7. Uncomment Firebase.initializeApp() in main.dart

// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       default:
//         throw UnsupportedError('DefaultFirebaseOptions: unsupported platform');
//     }
//   }
//
//   // TODO: Replace with values from flutterfire configure output
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey:            'REPLACE_WITH_REAL_ANDROID_API_KEY',
//     appId:             'REPLACE_WITH_REAL_ANDROID_APP_ID',
//     messagingSenderId: 'REPLACE_WITH_REAL_SENDER_ID',
//     projectId:         'mortgageus',
//     storageBucket:     'mortgageus.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey:            'REPLACE_WITH_REAL_IOS_API_KEY',
//     appId:             'REPLACE_WITH_REAL_IOS_APP_ID',
//     messagingSenderId: 'REPLACE_WITH_REAL_SENDER_ID',
//     projectId:         'mortgageus',
//     storageBucket:     'mortgageus.appspot.com',
//     iosBundleId:       'com.mortgageus.calculator',
//   );
// }
